//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageSchool.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Course", Namespace="http://schemas.datacontract.org/2004/07/WcfService.Models")]
    [System.SerializableAttribute()]
    public partial class Course : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClassCapacityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClassCapacity {
            get {
                return this.ClassCapacityField;
            }
            set {
                if ((this.ClassCapacityField.Equals(value) != true)) {
                    this.ClassCapacityField = value;
                    this.RaisePropertyChanged("ClassCapacity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseName {
            get {
                return this.CourseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseNameField, value) != true)) {
                    this.CourseNameField = value;
                    this.RaisePropertyChanged("CourseName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.ILanguageSchool", CallbackContract=typeof(LanguageSchool.ServiceReference.ILanguageSchoolCallback))]
    public interface ILanguageSchool {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILanguageSchool/GetNrOfCourses", ReplyAction="http://tempuri.org/ILanguageSchool/GetNrOfCoursesResponse")]
        int GetNrOfCourses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILanguageSchool/GetNrOfCourses", ReplyAction="http://tempuri.org/ILanguageSchool/GetNrOfCoursesResponse")]
        System.Threading.Tasks.Task<int> GetNrOfCoursesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILanguageSchool/GetTeacherName", ReplyAction="http://tempuri.org/ILanguageSchool/GetTeacherNameResponse")]
        string GetTeacherName(string courseName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILanguageSchool/GetTeacherName", ReplyAction="http://tempuri.org/ILanguageSchool/GetTeacherNameResponse")]
        System.Threading.Tasks.Task<string> GetTeacherNameAsync(string courseName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILanguageSchool/GetCoursesList", ReplyAction="http://tempuri.org/ILanguageSchool/GetCoursesListResponse")]
        System.Collections.Generic.List<LanguageSchool.ServiceReference.Course> GetCoursesList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILanguageSchool/GetCoursesList", ReplyAction="http://tempuri.org/ILanguageSchool/GetCoursesListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<LanguageSchool.ServiceReference.Course>> GetCoursesListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILanguageSchool/CourseSignIn", ReplyAction="http://tempuri.org/ILanguageSchool/CourseSignInResponse")]
        bool CourseSignIn(string courseName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILanguageSchool/CourseSignIn", ReplyAction="http://tempuri.org/ILanguageSchool/CourseSignInResponse")]
        System.Threading.Tasks.Task<bool> CourseSignInAsync(string courseName);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILanguageSchool/Subscribe")]
        void Subscribe();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILanguageSchool/Subscribe")]
        System.Threading.Tasks.Task SubscribeAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILanguageSchool/Unsubscribe")]
        void Unsubscribe();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILanguageSchool/Unsubscribe")]
        System.Threading.Tasks.Task UnsubscribeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILanguageSchoolCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILanguageSchool/Notify")]
        void Notify(string courseName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILanguageSchoolChannel : LanguageSchool.ServiceReference.ILanguageSchool, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LanguageSchoolClient : System.ServiceModel.DuplexClientBase<LanguageSchool.ServiceReference.ILanguageSchool>, LanguageSchool.ServiceReference.ILanguageSchool {
        
        public LanguageSchoolClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public LanguageSchoolClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public LanguageSchoolClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public LanguageSchoolClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public LanguageSchoolClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public int GetNrOfCourses() {
            return base.Channel.GetNrOfCourses();
        }
        
        public System.Threading.Tasks.Task<int> GetNrOfCoursesAsync() {
            return base.Channel.GetNrOfCoursesAsync();
        }
        
        public string GetTeacherName(string courseName) {
            return base.Channel.GetTeacherName(courseName);
        }
        
        public System.Threading.Tasks.Task<string> GetTeacherNameAsync(string courseName) {
            return base.Channel.GetTeacherNameAsync(courseName);
        }
        
        public System.Collections.Generic.List<LanguageSchool.ServiceReference.Course> GetCoursesList() {
            return base.Channel.GetCoursesList();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<LanguageSchool.ServiceReference.Course>> GetCoursesListAsync() {
            return base.Channel.GetCoursesListAsync();
        }
        
        public bool CourseSignIn(string courseName) {
            return base.Channel.CourseSignIn(courseName);
        }
        
        public System.Threading.Tasks.Task<bool> CourseSignInAsync(string courseName) {
            return base.Channel.CourseSignInAsync(courseName);
        }
        
        public void Subscribe() {
            base.Channel.Subscribe();
        }
        
        public System.Threading.Tasks.Task SubscribeAsync() {
            return base.Channel.SubscribeAsync();
        }
        
        public void Unsubscribe() {
            base.Channel.Unsubscribe();
        }
        
        public System.Threading.Tasks.Task UnsubscribeAsync() {
            return base.Channel.UnsubscribeAsync();
        }
    }
}
